from tkinter import *
window=Tk()
lbl=Label(window, text="My Full Name", fg='red', font=("Verdana", 16))
lbl.place(x=500, y=50)
lbl=Label(window, text="Enter Given Name", fg='red', font=("Verdana", 11))
lbl.place(x=350, y=85)
lbl=Label(window, text="Enter Middle Name", fg='red', font=("Verdana", 11))
lbl.place(x=350, y=120)
lbl=Label(window, text="Enter Last Name", fg='red', font=("Verdana", 11))
lbl.place(x=350, y=155)
lbl=Label(window, text="My Full Name is:", fg='red', font=("Verdana", 11))
lbl.place(x=350, y=200)

txtfld=Entry(window, text="This is Entry Widget", bd=3)
txtfld.place(x=600, y=85)
txtfld=Entry(window, text="This is Entry Widget", bd=3)
txtfld.place(x=600, y=120)
txtfld=Entry(window, text="This is Entry Widget", bd=3)
txtfld.place(x=600, y=155)
txtfld=Entry(window, text="This is Entry Widget", bd=3)
txtfld.place(x=600, y=200)

btn=Button(window, text="Show Full Name", fg='black')
btn.place(x=500, y=250)
btn=Button(window, text="Clear All", fg='black')
btn.place(x=520, y=290)

window.title('Midterm Exam Problem #2')
window.geometry("1280x800+10+10")
window.mainloop()